#create the nodePort service
apiVersion: v1
kind: Service
metadata:
  name: post-srv-node
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - name: post-srv-node
      protocol: TCP
      port: 4002
      targetPort: 4002  
