apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
# how does the deployment should behave
spec:
  #how many pods you want to create running some perticular container
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: aritra/query:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: ClusterIP # default is cluster ip
  selector:
    app: query
  ports:
    - name: query-srv
      protocol: TCP
      port: 4003
      targetPort: 4003
