#create the nodePort service
apiVersion: v1
kind: Service
metadata:
  name: query-srv-node
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - name: query-srv-node
      protocol: TCP
      port: 4003
      targetPort: 4003
